In [2]:
import pandas as pd

In [3]:
precipitation = pd.read_excel("Nabouwalu_rainfall.xlsx")

In [4]:
precipitation.head()

         lsd rain_24h max_air_temp min_air_temp rel_humidity wind_speed
0        NaT       mm           °c           °c            %        m/s
1 1990-01-01        0         28.5         24.4           63      5.144
2 1990-01-02        0           30         23.2           63     3.6008
3 1990-01-03        0         29.5         22.5           69     3.6008
4 1990-01-04     83.3         30.5         22.8           65     3.0864

In [5]:
precipitation = precipitation.drop(0)

In [6]:
# 1. Convert the date column to datetime (adjust 'Date' to your actual column name)
precipitation['Date'] = pd.to_datetime(precipitation['lsd'])

# 2. Set it as the index
precipitation = precipitation.set_index('Date')

# 3. Now you can extract the day of the year
precipitation['day_of_year'] = precipitation.index.dayofyear

# 4. Fill NaNs using the mean of that specific day across all years
precipitation['rain_24h'] = precipitation['rain_24h'].fillna(
    precipitation.groupby('day_of_year')['rain_24h'].transform('mean')
)

/tmp/ipykernel_1060/1010987979.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  precipitation['rain_24h'] = precipitation['rain_24h'].fillna(

In [7]:
precipitation

,lsd,rain_24h,max_air_temp,min_air_temp,rel_humidity,wind_speed,day_of_year
Date,,,,,,,
1990-01-01,1990-01-01,0.000000,28.5,24.4,63,5.144,1
1990-01-02,1990-01-02,0.000000,30,23.2,63,3.6008,2
1990-01-03,1990-01-03,0.000000,29.5,22.5,69,3.6008,3
1990-01-04,1990-01-04,83.300000,30.5,22.8,65,3.0864,4
1990-01-05,1990-01-05,22.500000,27.6,22.2,99,0,5
...,...,...,...,...,...,...,...
2025-04-26,2025-04-26,3.300000,31.2,24,69,NaN,116
2025-04-27,2025-04-27,7.300000,30.9,24.8,76,NaN,117
2025-04-28,2025-04-28,0.000000,30.9,25,73,NaN,118
2025-04-29,2025-04-29,9.337931,NaN,24.5,76,NaN,119
2025-04-30,2025-04-30,9.563333,NaN,NaN,NaN,NaN,120

In [8]:
precipitation.to_csv("precipitation_nabouwalu.csv")

In [9]:
print(precipitation.rain_24h.mean)

<bound method Series.mean of Date
1990-01-01     0.000000
1990-01-02     0.000000
1990-01-03     0.000000
1990-01-04    83.300000
1990-01-05    22.500000
                ...
2025-04-26     3.300000
2025-04-27     7.300000
2025-04-28     0.000000
2025-04-29     9.337931
2025-04-30     9.563333
Name: rain_24h, Length: 12904, dtype: float64>