<div><img src="https://github.com/digitalearthpacific/DigitalEarthPacific/blob/main/notebooks/DEP_LCAST/reference_materials/images/1B/1.a.png?raw=true" width="800"/></div>

# Activity Notebook Introduction to Digital Earth Pacific Abstraction Libary (DEPAL)
Intended for users of DEP. Completion of **'Activity Notebook Intro to Python'** as a prerequisite is recommended although not required. The notebook provides the foundations of Python more broadly. This **'Activity Notebook Intro to depal'** includes the introduction to [Digital Earth Pacific (DEP)](https://github.com/digitalearthpacific/DigitalEarthPacific/tree/main). We will again be working with Python within a Jupyter Notebook environment as the IDE. 

For questions regarding this notebook contact the author via https://github.com/nicholasmetherall

### Digital Earth Pacific (DEP) Notebook

Follow the example of code below to set up your Digital Earth Pacific (DEP) environment.

In [2]:
import sys
sys.path.append('../../')
import depal_mh as dep
import warnings
warnings.filterwarnings('ignore')

import geopandas as gpd
import numpy as np
import odc.geo.xr  # noqa: F401
import pandas as pd
import xarray as xr
from odc.stac import load
from pystac_client import Client
from shapely import geometry

<font color='blue'>1.1. Listing the countries within DEP and then the islands of the Republic of the Marshall Islands (RMI) boundary datasets in depal 

Your code goes in the cells below. Add more cells here by clicking on the + button above.

First let's list out the countries covered within Digital Earth Pacific (DEP):  

> dep.list_countries()

- Where *dep.* is the module   
- *list_countries()* is the function that converts requests or simple operations into an object. 

By running this block of code you can process data. This particular function returns a list of countries covered within the DEP module.   

> Input your code for 1.1 in this cell eg. `dep.list_countries()`

In [10]:
dep.list_countries()

                           0
0             American Samoa
1               Cook Islands
2                       Fiji
3           French Polynesia
4                       Guam
5                   Kiribati
6           Marshall Islands
7                 Micronesia
8                      Nauru
9              New Caledonia
10                      Niue
11  Northern Mariana Islands
12                     Palau
13          Papua New Guinea
14          Pitcairn Islands
15                     Samoa
16           Solomon Islands
17                   Tokelau
18                     Tonga
19                    Tuvalu
20                   Vanuatu
21         Wallis and Futuna

Now let's learn what boundary type are available for RMI... 

> Input your code for 1.1 in this cell eg. `dep.list_boundary_types('Marshall Islands')`
>

In [11]:
dep.list_boundary_types('Marshall Islands')

       0
0  Atoll

Now let's learn what Atolls are available for RMI... 

> `dep.list_country_boundary('Marshall' Islands', 'Atoll')`
>

In [17]:
dep.list_country_boundary('Marshall Islands', 'Atoll')

                   0
0       Ailinglaplap
1              Ailuk
2               Arno
3                Aur
4               Ebon
5           Enewetok
6              Jabat
7             Jaluit
8   Kili_Bikini_Ejit
9          Kwajalein
10               Lae
11               Lib
12            Likiep
13            Majuro
14          Maloelap
15             Mejit
16              Mili
17           Namorik
18              Namu
19          Rongelap
20              Ujae
21            Utirik
22             Wotho
23             Wotje

<font color='blue'>1.2. Getting a single RMI 'Atoll' dataset and configuring this as your area of interest

By running this block of code you can process data. This particular function returns a list of boundaries of islands in RMI covered within the DEP module. Note: these boundaries are based upon official RMI Government data. The list you have generated above is an example of how to call on default values stored within a library. 

Now that you have the list of datasets, you can try to access one of these datasets by calling it. This will load the data and configure it to be your area of interest for further analysis in depal. In order to do this, we will next seek to use: 
    
> `dep.get_country_admin_boundary('Marshall Islands', 'Atoll', 'insert Atoll name')` 

First type the module 'dep.' then type the function 'get_country_admin_boundary' then within the brackets you can search for a particular subset of the total list above. You can choose one from the list above and don't forgot to place it between quotations: e.g. "Koro".

> Input your code for 1.2 in this cell and input the name of an atoll from the list above.
>
Note: this will generate a long list of coordinates that map out the boundary.

In [18]:
# Example dep.get_country_admin_boundary('Marshall Islands', 'Atoll', 'Majuro')
dep.get_country_admin_boundary('Marshall Islands', 'Atoll', 'Majuro')

0    MULTIPOLYGON (((171.16516 7.16164, 171.16460 7.16185, 171.16397 7.16261, 171.16377 7.16344, 171.16440 7.16420, 171.16487 7.16441, 171.16530 7.16462, 171.16557 7.16469, 171.16628 7.16462, 171.16655 7.16448, 171.16689 7.16434, 171.16718 7.16420, 171.16751 7.16400, 171.16773 7.16379, 171.16766 7.16337, 171.16745 7.16289, 171.16724 7.16226, 171.16718 7.16178, 171.16696 7.16143, 171.16655 7.16136, 171.16571 7.16150, 171.16516 7.16164)), ((171.11778 7.18528, 171.11833 7.18528, 171.11833 7.18333, 171.11792 7.18354, 171.11765 7.18354, 171.11743 7.18361, 171.11694 7.18375, 171.11681 7.18396, 171.11673 7.18424, 171.11653 7.18465, 171.11626 7.18472, 171.11591 7.18472, 171.11563 7.18493, 171.11501 7.18528, 171.11556 7.18583, 171.11639 7.18611, 171.11667 7.18611, 171.11722 7.18556, 171.11749 7.18556, 171.11778 7.18528)), ((171.10750 7.19056, 171.10861 7.19056, 171.10916 7.19000, 171.10945 7.19000, 171.11028 7.18917, 171.11055 7.18917, 171.11084 7.18889, 171.11139 7.18889, 171.11250 7.18778, 171.11250 7.18750, 171.11166 7.18667, 171.11139 7.18667, 171.11112 7.18694, 171.11084 7.18694, 171.11055 7.18722, 171.11028 7.18722, 171.11000 7.18750, 171.10889 7.18750, 171.10861 7.18778, 171.10834 7.18778, 171.10806 7.18750, 171.10750 7.18750, 171.10722 7.18778, 171.10695 7.18778, 171.10667 7.18806, 171.10611 7.18806, 171.10527 7.18889, 171.10568 7.18967, 171.10555 7.18974, 171.10533 7.18988, 171.10445 7.19028, 171.10500 7.19083, 171.10527 7.19083, 171.10556 7.19111, 171.10667 7.19111, 171.10695 7.19083, 171.10722 7.19083, 171.10750 7.19056)), ((171.09723 7.19556, 171.09750 7.19583, 171.09778 7.19556, 171.09805 7.19556, 171.09889 7.19472, 171.10001 7.19472, 171.10140 7.19333, 171.10167 7.19333, 171.10222 7.19278, 171.10140 7.19194, 171.10072 7.19191, 171.10045 7.19198, 171.09996 7.19205, 171.09969 7.19198, 171.09947 7.19198, 171.09889 7.19167, 171.09862 7.19194, 171.09805 7.19194, 171.09750 7.19250, 171.09723 7.19250, 171.09694 7.19278, 171.09666 7.19278, 171.09639 7.19306, 171.09555 7.19306, 171.09528 7.19278, 171.09500 7.19278, 171.09416 7.19361, 171.09416 7.19417, 171.09424 7.19490, 171.09430 7.19524, 171.09438 7.19552, 171.09473 7.19611, 171.09528 7.19667, 171.09555 7.19667, 171.09584 7.19639, 171.09612 7.19639, 171.09694 7.19556, 171.09723 7.19556)), ((171.08917 7.20083, 171.08945 7.20055, 171.09000 7.20055, 171.09084 7.19972, 171.09111 7.19972, 171.09222 7.19861, 171.09250 7.19861, 171.09334 7.19778, 171.09334 7.19722, 171.09305 7.19694, 171.09305 7.19667, 171.09250 7.19611, 171.09222 7.19611, 171.09139 7.19694, 171.09111 7.19694, 171.09084 7.19722, 171.09000 7.19722, 171.08972 7.19750, 171.08945 7.19750, 171.08917 7.19778, 171.08888 7.19778, 171.08833 7.19833, 171.08806 7.19833, 171.08640 7.20000, 171.08611 7.20000, 171.08556 7.20055, 171.08528 7.20055, 171.08472 7.20111, 171.08444 7.20111, 171.08333 7.20222, 171.08305 7.20222, 171.08250 7.20278, 171.08250 7.20306, 171.08278 7.20333, 171.08278 7.20361, 171.08305 7.20389, 171.08389 7.20389, 171.08431 7.20362, 171.08507 7.20299, 171.08563 7.20264, 171.08583 7.20250, 171.08612 7.20230, 171.08659 7.20195, 171.08833 7.20139, 171.08888 7.20083, 171.08917 7.20083)), ((171.06583 7.22194, 171.06667 7.22194, 171.06694 7.22167, 171.06722 7.22167, 171.06778 7.22111, 171.06805 7.22111, 171.06833 7.22139, 171.06833 7.22167, 171.06917 7.22250, 171.06972 7.22194, 171.07001 7.22194, 171.07028 7.22222, 171.07195 7.22222, 171.07222 7.22194, 171.07361 7.22194, 171.07527 7.22028, 171.07723 7.22028, 171.07750 7.22000, 171.07889 7.22000, 171.08000 7.21889, 171.08055 7.21889, 171.08112 7.21833, 171.08112 7.21806, 171.08139 7.21778, 171.08139 7.21750, 171.08194 7.21694, 171.08194 7.21556, 171.08223 7.21528, 171.08223 7.21389, 171.08194 7.21361, 171.08194 7.21222, 171.08167 7.21195, 171.08167 7.21167, 171.08139 7.21139, 171.08139 7.20972, 171.08159 7.20903, 171.08156 7.20791, 171.08156 7.20722, 171.08164 7.20667, 171.08177 7.20639, 171.08199 7.20597, 171.08218 7.20576, 171.08218 7.20500, 171.08205 7.20472, 171.08185 7.20458, 171.08142 7.20445, 171.08055 7.20445, 171.08000 7.20500, 171.08028 7.20528, 171.08028 7.20556, 171.08055 7.20583, 171.08055 7.20611, 171.08028 7.20639, 171.08028 7.20667, 171.08000 7.20695, 171.08000 7.20778, 171.07973 7.20806, 171.07973 7.20945, 171.08000 7.20972, 171.08000 7.21167, 171.07973 7.21195, 171.07973 7.21222, 171.07834 7.21361, 171.07834 7.21389, 171.07805 7.21417, 171.07805 7.21445, 171.07723 7.21528, 171.07723 7.21556, 171.07695 7.21583, 171.07666 7.21583, 171.07639 7.21611, 171.07584 7.21611, 171.07556 7.21639, 171.07500 7.21639, 171.07472 7.21667, 171.07445 7.21667, 171.07388 7.21722, 171.07361 7.21722, 171.07306 7.21778, 171.07250 7.21778, 171.07222 7.21806, 171.07195 7.21806, 171.07167 7.21833, 171.07140 7.21833, 171.07111 7.21861, 171.07028 7.21861, 171.07001 7.21889, 171.06972 7.21889, 171.06944 7.21861, 171.06917 7.21861, 171.06889 7.21889, 171.06805 7.21889, 171.06778 7.21917, 171.06722 7.21917, 171.06680 7.21923, 171.06604 7.21931, 171.06549 7.21931, 171.06465 7.21917, 171.06424 7.21903, 171.06278 7.21861, 171.06201 7.21847, 171.06139 7.21820, 171.06062 7.21778, 171.05986 7.21722, 171.05882 7.21618, 171.05841 7.21570, 171.05785 7.21542, 171.05771 7.21528, 171.05750 7.21472, 171.05722 7.21472, 171.05667 7.21417, 171.05640 7.21417, 171.05611 7.21389, 171.05583 7.21389, 171.05556 7.21361, 171.05499 7.21361, 171.05472 7.21333, 171.05472 7.21306, 171.05499 7.21278, 171.05499 7.21250, 171.05528 7.21222, 171.05499 7.21195, 171.05499 7.21167, 171.05444 7.21167, 171.05417 7.21139, 171.05389 7.21139, 171.05360 7.21111, 171.05360 7.21056, 171.05194 7.20889, 171.05139 7.20889, 171.05112 7.20917, 171.05083 7.20917, 171.05055 7.20945, 171.05055 7.20972, 171.05028 7.21000, 171.05028 7.21195, 171.05055 7.21222, 171.05055 7.21250, 171.05194 7.21389, 171.05251 7.21389, 171.05278 7.21417, 171.05306 7.21417, 171.05360 7.21472, 171.05360 7.21500, 171.05389 7.21528, 171.05389 7.21556, 171.05528 7.21694, 171.05556 7.21667, 171.05611 7.21667, 171.05624 7.21694, 171.05681 7.21729, 171.05730 7.21792, 171.05771 7.21903, 171.05833 7.21986, 171.05861 7.22000, 171.05888 7.22028, 171.05888 7.22056, 171.05945 7.22111, 171.05972 7.22111, 171.06000 7.22139, 171.06027 7.22139, 171.06056 7.22167, 171.06084 7.22167, 171.06111 7.22194, 171.06223 7.22194, 171.06250 7.22222, 171.06278 7.22222, 171.06305 7.22250, 171.06334 7.22250, 171.06361 7.22278, 171.06473 7.22278, 171.06528 7.22222, 171.06555 7.22222, 171.06583 7.22194)), ((171.20223 7.06333, 171.20250 7.06306, 171.20305 7.06306, 171.20334 7.06278, 171.20416 7.06278, 171.20444 7.06250, 171.20528 7.06250, 171.20555 7.06222, 171.20612 7.06222, 171.20639 7.06194, 171.20694 7.06194, 171.20723 7.06167, 171.20805 7.06167, 171.20833 7.06139, 171.21001 7.06139, 171.21028 7.06111, 171.21056 7.06139, 171.21111 7.06139, 171.21140 7.06167, 171.21195 7.06167, 171.21249 7.06111, 171.21306 7.06111, 171.21333 7.06083, 171.21417 7.06083, 171.21445 7.06056, 171.21472 7.06056, 171.21500 7.06028, 171.21527 7.06028, 171.21584 7.05972, 171.21666 7.05972, 171.21695 7.05944, 171.21750 7.05944, 171.21805 7.05889, 171.21834 7.05889, 171.21916 7.05806, 171.21945 7.05806, 171.22055 7.05694, 171.22139 7.05694, 171.22166 7.05667, 171.22194 7.05667, 171.22223 7.05639, 171.22250 7.05639, 171.22278 7.05611, 171.22305 7.05611, 171.22333 7.05583, 171.22389 7.05583, 171.22417 7.05556, 171.22528 7.05556, 171.22556 7.05528, 171.22640 7.05528, 171.22667 7.05500, 171.22722 7.05500, 171.22749 7.05472, 171.22833 7.05472, 171.22861 7.05444, 171.22945 7.05444, 171.22972 7.05417, 171.23056 7.05417, 171.23084 7.05444, 171.23195 7.05444, 171.23277 7.05528, 171.23306 7.05528, 171.23334 7.05500, 171.23473 7.05500, 171.23500 7.05528, 171.23639 7.05528, 171.23666 7.05556, 171.23694 7.05556, 171.23723 7.05528, 171.23889 7.05528, 171.23917 7.05556, 171.24056 7.05556, 171.24083 7.05583, 171.24167 7.05583, 171.24194 7.05611, 171.24222 7.05611, 171.24249 7.05639, 171.24278 7.05639, 171.24306 7.05667, 171.24445 7.05667, 171.24472 7.05694, 171.24500 7.05694, 171.24556 7.05750, 171.24667 7.05750, 171.24722 7.05806, 171.24889 7.05806, 171.24916 7.05833, 171.24945 7.05833, 171.24973 7.05861, 171.25000 7.05861, 171.25084 7.05944, 171.25139 7.05944, 171.25166 7.05972, 171.25194 7.05972, 171.25223 7.06000, 171.25278 7.06000, 171.25305 7.06028, 171.25362 7.06028, 171.25389 7.06056, 171.25444 7.06056, 171.25472 7.06083, 171.25501 7.06083, 171.25528 7.06111, 171.25555 7.06111, 171.25583 7.06139, 171.25610 7.06139, 171.25639 7.06167, 171.25667 7.06167, 171.25722 7.06222, 171.25833 7.06222, 171.25861 7.06194, 171.25917 7.06194, 171.26028 7.06306, 171.26056 7.06306, 171.26083 7.06333, 171.26111 7.06333, 171.26138 7.06361, 171.26195 7.06361, 171.26222 7.06389, 171.26250 7.06389, 171.26277 7.06417, 171.26361 7.06417, 171.26389 7.06444, 171.26473 7.06444, 171.26500 7.06472, 171.26584 7.06472, 171.26611 7.06500, 171.26666 7.06500, 171.26694 7.06528, 171.26805 7.06528, 171.26833 7.06556, 171.26889 7.06556, 171.26917 7.06584, 171.27000 7.06584, 171.27028 7.06611, 171.27167 7.06611, 171.27194 7.06639, 171.27251 7.06639, 171.27278 7.06667, 171.27361 7.06667, 171.27390 7.06695, 171.27445 7.06695, 171.27472 7.06722, 171.27556 7.06722, 171.27583 7.06750, 171.27611 7.06750, 171.27638 7.06722, 171.27667 7.06722, 171.27695 7.06750, 171.27750 7.06750, 171.27777 7.06778, 171.27806 7.06778, 171.27834 7.06806, 171.27861 7.06806, 171.27916 7.06861, 171.27945 7.06861, 171.27972 7.06889, 171.28055 7.06889, 171.28084 7.06917, 171.28139 7.06917, 171.28166 7.06945, 171.28250 7.06945, 171.28278 7.06972, 171.28334 7.06972, 171.28362 7.06945, 171.28389 7.06945, 171.28416 7.06917, 171.28444 7.06917, 171.28473 7.06945, 171.28528 7.06945, 171.28555 7.06972, 171.28639 7.06972, 171.28667 7.06945, 171.28751 7.06945, 171.28778 7.06972, 171.28833 7.06972, 171.28861 7.07000, 171.29083 7.07000, 171.29111 7.06972, 171.29167 7.06972, 171.29195 7.07000, 171.29334 7.07000, 171.29361 7.07028, 171.29556 7.07028, 171.29584 7.07056, 171.29611 7.07056, 171.29639 7.07028, 171.29778 7.07028, 171.29805 7.07056, 171.30222 7.07056, 171.30251 7.07083, 171.30306 7.07083, 171.30333 7.07111, 171.30444 7.07111, 171.30472 7.07139, 171.30528 7.07139, 171.30556 7.07167, 171.30611 7.07167, 171.30640 7.07195, 171.30695 7.07195, 171.30722 7.07222, 171.30806 7.07222, 171.30833 7.07250, 171.30917 7.07250, 171.30945 7.07278, 171.31000 7.07278, 171.31027 7.07306, 171.31111 7.07306, 171.31139 7.07333, 171.31195 7.07333, 171.31223 7.07361, 171.31361 7.07361, 171.31389 7.07389, 171.31416 7.07389, 171.31444 7.07417, 171.31500 7.07417, 171.31528 7.07445, 171.31583 7.07445, 171.31612 7.07472, 171.31639 7.07472, 171.31667 7.07500, 171.31722 7.07500, 171.31805 7.07583, 171.31860 7.07583, 171.31889 7.07611, 171.31944 7.07611, 171.31972 7.07639, 171.32140 7.07639, 171.32167 7.07667, 171.32195 7.07667, 171.32222 7.07695, 171.32278 7.07695, 171.32306 7.07722, 171.32333 7.07722, 171.32361 7.07750, 171.32388 7.07750, 171.32417 7.07722, 171.32584 7.07722, 171.32611 7.07750, 171.32666 7.07750, 171.32695 7.07722, 171.32889 7.07722, 171.32916 7.07750, 171.32944 7.07750, 171.32973 7.07778, 171.33000 7.07778, 171.33083 7.07861, 171.33083 7.07917, 171.33167 7.08000, 171.33223 7.08000, 171.33250 7.08028, 171.33278 7.08028, 171.33305 7.08000, 171.33362 7.08000, 171.33389 7.08028, 171.33444 7.08028, 171.33472 7.08056, 171.33501 7.08056, 171.33528 7.08083, 171.33556 7.08083, 171.33583 7.08111, 171.33611 7.08111, 171.33640 7.08139, 171.33833 7.08139, 171.33861 7.08167, 171.33888 7.08139, 171.33972 7.08139, 171.34000 7.08167, 171.34084 7.08167, 171.34111 7.08194, 171.34277 7.08194, 171.34305 7.08222, 171.34389 7.08222, 171.34416 7.08250, 171.34500 7.08250, 171.34528 7.08278, 171.34639 7.08278, 171.34666 7.08306, 171.34694 7.08306, 171.34723 7.08333, 171.34750 7.08333, 171.34805 7.08389, 171.34805 7.08417, 171.34862 7.08472, 171.34889 7.08472, 171.34944 7.08417, 171.34972 7.08417, 171.35001 7.08389, 171.35140 7.08389, 171.35167 7.08417, 171.35306 7.08417, 171.35361 7.08361, 171.35472 7.08361, 171.35500 7.08389, 171.35527 7.08389, 171.35584 7.08444, 171.35638 7.08444, 171.35667 7.08472, 171.35806 7.08472, 171.35834 7.08500, 171.35861 7.08500, 171.35889 7.08528, 171.35916 7.08528, 171.35973 7.08472, 171.36055 7.08472, 171.36084 7.08500, 171.36139 7.08500, 171.36166 7.08528, 171.36194 7.08528, 171.36250 7.08583, 171.36278 7.08583, 171.36305 7.08611, 171.36305 7.08639, 171.36417 7.08750, 171.36472 7.08694, 171.36528 7.08694, 171.36556 7.08667, 171.36583 7.08694, 171.36610 7.08694, 171.36639 7.08667, 171.36667 7.08667, 171.36694 7.08639, 171.36833 7.08639, 171.36861 7.08611, 171.36917 7.08611, 171.36945 7.08583, 171.37000 7.08639, 171.37029 7.08639, 171.37056 7.08667, 171.37111 7.08667, 171.37138 7.08694, 171.37222 7.08694, 171.37250 7.08722, 171.37306 7.08722, 171.37334 7.08750, 171.37416 7.08750, 171.37445 7.08778, 171.37528 7.08778, 171.37611 7.08861, 171.37723 7.08861, 171.37833 7.08972, 171.37833 7.09028, 171.37862 7.09056, 171.37862 7.09083, 171.37889 7.09111, 171.37889 7.09194, 171.37917 7.09236, 171.37917 7.09250, 171.37862 7.09306, 171.37862 7.09361, 171.37917 7.09417, 171.37917 7.09556, 171.37889 7.09583, 171.37889 7.09611, 171.37833 7.09667, 171.37833 7.09695, 171.37862 7.09722, 171.37862 7.09834, 171.37833 7.09861, 171.37833 7.09889, 171.37805 7.09917, 171.37805 7.09945, 171.37778 7.09972, 171.37778 7.10000, 171.37666 7.10111, 171.37666 7.10139, 171.37555 7.10250, 171.37555 7.10333, 171.37528 7.10361, 171.37528 7.10389, 171.37473 7.10445, 171.37389 7.10500, 171.37361 7.10472, 171.37277 7.10472, 171.37195 7.10528, 171.37111 7.10611, 171.37111 7.10667, 171.37083 7.10694, 171.37083 7.10722, 171.36833 7.10972, 171.36833 7.11000, 171.36806 7.11028, 171.36806 7.11056, 171.36667 7.11194, 171.36667 7.11222, 171.36639 7.11250, 171.36639 7.11333, 171.36583 7.11389, 171.36583 7.11417, 171.36556 7.11444, 171.36556 7.11500, 171.36528 7.11528, 171.36528 7.11556, 171.36501 7.11583, 171.36501 7.11639, 171.36472 7.11667, 171.36472 7.11694, 171.36444 7.11722, 171.36444 7.11750, 171.36417 7.11778, 171.36417 7.11834, 171.36362 7.11889, 171.36362 7.11917, 171.36333 7.11944, 171.36333 7.11972, 171.36194 7.12111, 171.36166 7.12111, 171.36139 7.12139, 171.36112 7.12139, 171.36055 7.12195, 171.36028 7.12195, 171.36000 7.12222, 171.35806 7.12222, 171.35777 7.12250, 171.35695 7.12250, 171.35667 7.12278, 171.35638 7.12278, 171.35611 7.12250, 171.35584 7.12250, 171.35556 7.12278, 171.35527 7.12278, 171.35500 7.12305, 171.35388 7.12305, 171.35361 7.12278, 171.35167 7.12278, 171.35140 7.12250, 171.35111 7.12278, 171.35001 7.12278, 171.34972 7.12250, 171.34805 7.12250, 171.34778 7.12278, 171.34723 7.12278, 171.34694 7.12250, 171.34584 7.12250, 171.34555 7.12222, 171.34473 7.12222, 171.34445 7.12195, 171.34416 7.12195, 171.34361 7.12139, 171.34305 7.12139, 171.34277 7.12167, 171.34250 7.12167, 171.34222 7.12195, 171.34195 7.12195, 171.34166 7.12222, 171.34139 7.12222, 171.34111 7.12195, 171.34084 7.12195, 171.34000 7.12111, 171.34000 7.12083, 171.33917 7.12000, 171.33888 7.12000, 171.33833 7.12055, 171.33833 7.12139, 171.33861 7.12167, 171.33861 7.12278, 171.34027 7.12445, 171.34056 7.12445, 171.34084 7.12472, 171.34111 7.12472, 171.34416 7.12583, 171.34445 7.12583, 171.34473 7.12611, 171.34584 7.12611, 171.34612 7.12583, 171.34612 7.12556, 171.34639 7.12528, 171.34694 7.12528, 171.34723 7.12556, 171.34805 7.12556, 171.34833 7.12583, 171.34862 7.12583, 171.34889 7.12611, 171.35083 7.12639, 171.35111 7.12639, 171.35140 7.12611, 171.35306 7.12611, 171.35333 7.12583, 171.35611 7.12583, 171.35638 7.12611, 171.35695 7.12611, 171.35722 7.12639, 171.35750 7.12639, 171.35806 7.12695, 171.35861 7.12639, 171.35973 7.12639, 171.36000 7.12611, 171.36055 7.12611, 171.36084 7.12583, 171.36139 7.12583, 171.36223 7.12667, 171.36250 7.12667, 171.36305 7.12611, 171.36305 7.12583, 171.36333 7.12556, 171.36333 7.12528, 171.36417 7.12445, 171.36417 7.12417, 171.36472 7.12361, 171.36472 7.12333, 171.36528 7.12278, 171.36528 7.12250, 171.36556 7.12222, 171.36556 7.12167, 171.36583 7.12139, 171.36583 7.12111, 171.36610 7.12083, 171.36610 7.12055, 171.36639 7.12028, 171.36639 7.11972, 171.36667 7.11944, 171.36667 7.11805, 171.36694 7.11778, 171.36694 7.11722, 171.36833 7.11583, 171.36833 7.11472, 171.36945 7.11361, 171.36945 7.11306, 171.37000 7.11250, 171.37000 7.11222, 171.37029 7.11194, 171.37056 7.11194, 171.37083 7.11167, 171.37138 7.11167, 171.37222 7.11083, 171.37250 7.11083, 171.37723 7.10611, 171.37723 7.10583, 171.37750 7.10556, 171.37750 7.10528, 171.37889 7.10389, 171.37889 7.10361, 171.37917 7.10333, 171.37917 7.10306, 171.37972 7.10250, 171.37972 7.10222, 171.38001 7.10195, 171.38001 7.10167, 171.38028 7.10139, 171.38028 7.10083, 171.38055 7.10056, 171.38055 7.10028, 171.38083 7.10000, 171.38083 7.09972, 171.38110 7.09945, 171.38110 7.09917, 171.38139 7.09889, 171.38139 7.09861, 171.38167 7.09834, 171.38167 7.09722, 171.38194 7.09695, 171.38194 7.09639, 171.38222 7.09611, 171.38222 7.09583, 171.38278 7.09528, 171.38278 7.09472, 171.38333 7.09417, 171.38333 7.09389, 171.38361 7.09361, 171.38361 7.09306, 171.38390 7.09278, 171.38390 7.09250, 171.38417 7.09222, 171.38417 7.09194, 171.38445 7.09167, 171.38445 7.08917, 171.38390 7.08861, 171.38306 7.08861, 171.38251 7.08806, 171.38222 7.08806, 171.38167 7.08750, 171.38110 7.08750, 171.38083 7.08722, 171.38055 7.08722, 171.37889 7.08556, 171.37862 7.08556, 171.37805 7.08500, 171.37778 7.08500, 171.37750 7.08472, 171.37723 7.08472, 171.37694 7.08444, 171.37666 7.08444, 171.37528 7.08417, 171.37500 7.08417, 171.37473 7.08389, 171.37306 7.08389, 171.37277 7.08361, 171.37250 7.08361, 171.37222 7.08333, 171.37195 7.08333, 171.37167 7.08361, 171.37138 7.08361, 171.37111 7.08333, 171.37056 7.08333, 171.37029 7.08306, 171.36861 7.08306, 171.36667 7.08333, 171.36667 7.08361, 171.36528 7.08278, 171.36444 7.08278, 171.36417 7.08306, 171.36362 7.08306, 171.36333 7.08333, 171.36305 7.08333, 171.36223 7.08250, 171.36166 7.08250, 171.36139 7.08278, 171.36084 7.08278, 171.36055 7.08306, 171.36000 7.08306, 171.35973 7.08278, 171.35916 7.08278, 171.35889 7.08250, 171.35638 7.08250, 171.35611 7.08222, 171.35556 7.08222, 171.35527 7.08194, 171.35500 7.08222, 171.35445 7.08222, 171.35417 7.08194, 171.35388 7.08194, 171.35361 7.08167, 171.35278 7.08167, 171.35249 7.08139, 171.35222 7.08139, 171.35194 7.08111, 171.34833 7.08111, 171.34778 7.08056, 171.34555 7.08028, 171.34277 7.08000, 171.34250 7.08000, 171.34222 7.07972, 171.34139 7.07972, 171.34111 7.07944, 171.34056 7.07944, 171.34000 7.07889, 171.33749 7.07889, 171.33722 7.07861, 171.33695 7.07861, 171.33640 7.07917, 171.33611 7.07917, 171.33528 7.07833, 171.33472 7.07833, 171.33417 7.07778, 171.33389 7.07778, 171.33333 7.07722, 171.33305 7.07722, 171.33278 7.07695, 171.33223 7.07695, 171.33167 7.07639, 171.33139 7.07639, 171.33112 7.07611, 171.33083 7.07611, 171.33000 7.07528, 171.32973 7.07528, 171.32944 7.07500, 171.32916 7.07500, 171.32889 7.07472, 171.32861 7.07472, 171.32834 7.07445, 171.32777 7.07445, 171.32750 7.07417, 171.32723 7.07417, 171.32695 7.07389, 171.32556 7.07389, 171.32527 7.07361, 171.32083 7.07361, 171.32056 7.07333, 171.31805 7.07250, 171.31778 7.07222, 171.31722 7.07222, 171.31667 7.07167, 171.31583 7.07167, 171.31555 7.07139, 171.31528 7.07139, 171.31473 7.07083, 171.31389 7.07083, 171.31361 7.07056, 171.31305 7.07056, 171.31250 7.07000, 171.31166 7.07000, 171.31139 7.07028, 171.31084 7.07028, 171.31056 7.07000, 171.30917 7.07000, 171.30888 7.06972, 171.30695 7.06972, 171.30667 7.06945, 171.30611 7.06945, 171.30583 7.06917, 171.30556 7.06917, 171.30528 7.06889, 171.30499 7.06889, 171.30472 7.06861, 171.30306 7.06806, 171.30083 7.06778, 171.30055 7.06806, 171.30000 7.06806, 171.29916 7.06750, 171.29834 7.06750, 171.29778 7.06750, 171.29750 7.06722, 171.29666 7.06722, 171.29639 7.06750, 171.29445 7.06750, 171.29417 7.06722, 171.29388 7.06750, 171.29250 7.06750, 171.29222 7.06778, 171.29195 7.06778, 171.29167 7.06750, 171.28999 7.06750, 171.2

<font color='blue'>1.3. Define this dataset within a new variable

To make it easier to use this dataset going forward through the activity, you can define it within a variable. 
    
To do this, save the code from 1.2 into a variable name. The variable name can be the name of the island you have chosen: e.g. Majuro. 
    
Then after typing the island you have chosen input " = " and then make this equal the code you have entered in 1.2.

So in this example, the code input would be:
    
> `Majuro = dep.get_country_admin_boundary('Marshall Islands', 'Atoll', 'Majuro')`
    
This new variable allows you to store the results from 1.2 and easily use them going forward. 
    
> Input your code for 1.3 in this cell eg. `Majuro = dep.get_country_admin_boundary('Marshall Islands', 'Atoll', 'Majuro')`

In [43]:
#Majuro = dep.get_country_admin_boundary('Marshall Islands', 'Atoll', 'Majuro')

<font color='blue'>1.4. Visualising and exploring RMI dataset with an interactive map

Now that you have accessed this data and downloaded this data you can now visualise this data in an interactive map as part of the leafmap functionality within Python notebooks. This function has been wrapped and simplified in DEP using the **explore()** function. 

Try to input your area of interest variable followed by: 
    
> .explore()
    
Once loaded, try out this interactive map by scrolling in and out and panning around to different areas of the basemap.
    
> Input your code for 1.4 in this cell eg. `Majuro.explore()`

<font color='blue'>2. Practicing this workflow for another atoll.

Now through this workflow you have learned how to use the following functions and define variables:
    
> 1. dep.list_boundary_types('Marshall Islands') - List the boundary datasets available for a specific country
> 2. dep.list_country_boundary('Marshall Islands', 'Atoll') - List the atoll boundaries available
> 3. dep.get_country_boundary('Marshall Islands', 'Atoll', 'insert atoll name from list') - Get one of the boundary datasets and use configure this to be your area of interest 
> 3. var = ... - Define this boundary dataset within a new variable
> 4. var.explore() - Explore this boundary dataset within an interactive map
    
Practice this workflow by repeating this step but this time, choose a different atoll.

<font color='blue'>2.1 Get or download another atoll boundary dataset

First, you will be following the step same to the last code inputted for activity 1.1 :

> `dep.list_country_boundary('insert parameters required inside quotation marks and separated by commas')`
    
Running this should list the atolls again.

<font color='blue'>2.2 Get a single division boundary for your aoi following a similar workflow to 1.2:
> `dep.get_country_boundary('insert parameters required inside quotation marks and separated by commas')`

<font color='blue'>2.3 Define this division boundary within a new variable using a similar step to 1.3:

<font color='blue'>2.4 Explore this division boundary using a similar step to 1.4:

<font color='blue'>3. Uploading your own area of interest in geojson format:

While it is useful to perform analysis within government administrative boundaries, we may also have work requiring us to perform analysis within custom boundaries or "areas of interest (AOIs)". In this activity you will learn how to upload your own goejson for the analysis:

<font color='blue'>3.1. Loading a geojson:

If you have your own geojson file for an aoi in RMI already, you can simply drag and drop it into this Jupyter folder - if you do not have a .geojson file already, you can use one we have prepared earlier:   
    
> "majuro.geojson"
    
<div><img src="https://github.com/digitalearthpacific/depal/blob/main/Marshall_Islands/intro-activities/reference_materials/laura_2_geojson.PNG?raw=true" width="400"/></div>

Try double clicking on your geojson file to open it and to verify that it is the area that you are seeking to analyse: 

<div><img src="https://github.com/digitalearthpacific/depal/blob/main/Marshall_Islands/intro-activities/reference_materials/laura_explorer.PNG?raw=true" width="800"/></div>

<font color='blue'>3.2. Loading geojson into depal 
    
To load this geojson area into depal use the function: 
    
> `dep.get_area_from_geojson("laura_extent.geojson")` 
    
Note, do not forget to place your filename within quotations "..." including the extension
    
> Input your code for 3.2 in this cell eg. `dep.get_area_from_geojson("...")`

<font color='blue'>3.3. Define this new aoi within a new variable (refer to 2.3)

<font color='blue'>3.4 Explore this aoi using the explore() function (refer to 2.4):

<font color='blue'>3.5 Repeat these steps from 3.2-3.4 but this time use the majuro_town_centre_extent.geojson and the eneko_extent.geojson to explore the different parts of Majuro:

#### **<font color='green'>Well done...**

You have learned how to set up your area of interest in depal. Now we will begin working with the satellite imagery data.

Note that there are a range of different datasets and models. For this activity we are most interested in the **Sentinel 2** dataset. 
This data has been pre-processed as a GeoMAD product for use in this workshop. This will be explained in the workshop.

### <font color='blue'>Learning about the European Space Agency Sentinel 2 Satellite.</font>
<font color = 'blue' ></font>

The main satellite data we will be using for this workshop is from the Copernicus Sentinel 2 satellite dataset as shown in figure s.2.a. 

<div><img src="https://github.com/digitalearthpacific/DigitalEarthPacific/blob/main/notebooks/DEP_LCAST/reference_materials/images/1B/Sentinel.1.jpg?raw=true" width="600"/></div>

Figure S.2.a. Provides an overview of Sentinel 2 satellite:

The table in figure S.2.b. provides a list of the different bands or spectral wavelengths captured by the Sentinel 2 satellite. We will be using these for our analyses within the workshop. 

The bands are measured in wavelengths with unit measurements of nanometers. Visible light is measured in nanometers (nm). A nanometer is a unit of length equal to one billionth of a meter.

<font color='blue'>4.1. Learning about spectral bands: 

These include optical bands we can see with the human eye:
- (B2) Blue = 458-523 nm
- (B3) Green = 543-578 nm 
- (B4) Red = 650-680 nm

And infrared bands that cannot be detected by the human eye:
- (B8) Near Infrared or NIR = 785-900 nm
- (B11) Shortwave Infrared 1 or SWIR 1 = 1565-1655 nm

For the full list see Figure S.2.b.

<div><img src="https://github.com/digitalearthpacific/DigitalEarthPacific/blob/main/notebooks/DEP_LCAST/reference_materials/images/1B/Sentinel.2.png?raw=true="600" width="580"/></div>

Figure S.2.b. Table list of spectral bands captured by sensors on the Sentinel 2 satellite

A visualisation of these bands from the table in S.2.b. is visualised as a spectrum in figure S.2.c.
    
    
    
    
    
<div><img src="https://github.com/digitalearthpacific/DigitalEarthPacific/blob/main/notebooks/DEP_LCAST/reference_materials/images/1B/Sentinel.3.jpg?raw=true="600" width="580"/></div>

Figure S.2.c. The spectrum of different wavelengths visualised:

<font color='blue'>4.2. Get annual Red Green and Blue (RGB) data for your aoi:
    
Now we can get our most recent satellite data using depal for our predefined aoi. The function to load the red green and blue bands of satellite data is as follows:

> `dep.get_latest(aoi)`
    
> Input your code for 4.1 in this cell eg. `dep.get_latest(aoi)`
    
For the first input within the brackets you will first need to input your own aoi variable where it says 'aoi'.

<font color='blue'>4.3 Define your answer from 4.2 within a new variable:
    
> For example data = ....

<font color='blue'>4.3 Plot this data for visualisation:
    
Plotting this data will allow you to see the results. Here we use :
    
> `dep.visualise(data, cmap=None)` 
    
Where data is the variable you defined in 4.3. 

Note this will generate a series of satellite imagery data for 2024 since you have loaded the most recent data. In the next activities we will be learning how to generate more data across different timescales.

#### **<font color='green'>Congratulations you have now completed the intro to depal notebook activity.**

<font color='purple'>5.1 Optional bonus activity: if you have finished all the other activities and still have time before the next part of the course, you can master the workflows of 1.1-1.4 and 2.1-2.4 by practicing these steps one more time but this time for a different area of interest.

<font color='purple'>5.2 Optional bonus activity: with the result of 5.1 plot this in rgb:

#### **<font color='green'>Excellent work!!!**
    
You have also completed the bonus activities.